### ISSUE TITLE
Authorization: Bearer HEADER missing in entrypoint.sh

### ISSUE THREAD

**Issue by ezYakaEagle442** [lgmorand/self-hosted-runner-dockerized#1]
Hello LG,

FYI

BAD : 
```sh
curl -s X -H POST "Authorization: $TOKEN" https://api.github.com/repos/${OWNER}/${REPO}/actions/runners/registration-token
{
  "message": "Must have admin rights to Repository.",
  "documentation_url": "https://docs.github.com/rest/reference/actions#get-a-self-hosted-runner-for-a-repository"
}
```

Good:
```sh
curl -s -X POST -H "Authorization: Bearer $TOKEN" https://api.github.com/repos/${OWNER}/${REPO}/actions/runners/registration-token

{
  "token": "Toto42Toto42Toto42Toto42Toto42",
  "expires_at": "2022-12-10T18:13:05.796+01:00"
}
```

PS: I would also suggest you to add in the README this tip:
Go to [https://github.com/settings/tokens](https://github.com/settings/tokens) to generate your own PAT named: TOKEN
With repo, workflow scope authorizations

Pinpin ;)

**Comment by lgmorand** [comment]
no need to add a readme, people bought the book ;-) everything is explained in it

**Comment by ezYakaEagle442** [comment]
also Fine-grained personal access tokens does not work

**Comment by lgmorand** [comment]
ca on est d'accord, jamais réussi à les faire marcher pour quoi que ce soit

**Comment by lgmorand** [comment]
t'as pas besoin du Bearer header. ca fonctionne parfaitement tel quel mais t'as oublié un mot clé on dirait ;). je viens de lancer un run du repo actuel et ca fonctionne nickel. tu me fais des fausses issues. **ca mérite le supplice de la grande cale moussaillon !!!**

`C:\Users\lgmor>docker run --env OWNER=lgmorand --env TOKEN=ghp_0hXXXXXXX --env NAME=redtower-runner --env REPO=self-hosted-runner-dockerized lgmorand/self-hosted-runnner
Unable to find image 'lgmorand/self-hosted-runnner:latest' locally
latest: Pulling from lgmorand/self-hosted-runnner
eaead16dc43b: Pull complete
d9289446e865: Pull complete
18186045105d: Pull complete
6b2b447280b7: Pull complete
27b7029147e8: Pull complete
442e49282363: Pull complete
0b0752906d04: Pull complete
Digest: sha256:d6cf1f7b0efa5d0f09e9d85f60a1369b81d3b152ced7d780c0b6dc4d6503b575
Status: Downloaded newer image for lgmorand/self-hosted-runnner:latest

--------------------------------------------------------------------------------
|        ____ _ _   _   _       _          _        _   _                      |
|       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
|      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
|      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
|       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
|                                                                              |
|                       Self-hosted runner registration                        |
|                                                                              |
--------------------------------------------------------------------------------

# Authentication


√ Connected to GitHub

# Runner Registration



√ Runner successfully added
√ Runner connection is good

# Runner settings


√ Settings Saved.


√ Connected to GitHub

2022-12-10 20:09:04Z: Listening for Jobs
`

**Comment by ezYakaEagle442** [comment]
@lgmorand indeed my bad j'avais oublié le mot clé token ...

çà marche en fait !
curl -s -X POST -H "Authorization: **token** $GHA_RUNNER_PAT" "https://api.github.com/repos/${OWNER}/${REPO}/actions/runners/registration-token"
